version: '3.8'
services:
  raycast:
    container_name: raycast
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 1.1.1.1
    volumes:
      - "$PWD/raycast_proxy:/project/raycast_proxy"
      - "$PWD/logs:/project/logs"
    command: --reload
    env_file:
      - .env
networks:
  default:
    external: true
    name: nginx_proxy
