name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases and pushing changes
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -e ".[dev]" --system  # Install dev dependencies for building

      - name: Run tests
        run: |
          uv run pytest tests/test_endpoints.py -v

      - name: Build package
        run: |
          uv build
          
      - name: Extract release notes
        id: release_notes
        run: |
          # Extract the latest version's release notes from CHANGELOG.md
          awk '/^## \[[0-9]+\.[0-9]+\.[0-9]+\]/ {if(p){exit}; p=1; next} p' CHANGELOG.md > release_notes.txt
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
          body_path: release_notes.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
